### ISSUE TITLE
[Feature Request] polar bear meat

### ISSUE THREAD

**Issue by ItzEnderYT0** [bpteammc/arcticmod#19]
add raw and cooked polarbear meat

Raw Meat: 3 Hunger
Cooked meat: 9 Hunger

**Comment by UKMinecrafted** [comment]
yea... we don't have polar bears...

**Comment by ItzEnderYT0** [comment]
> yea... we don't have polar bears...

but polar bears are from arctic? so it's a good food adition

**Comment by UKMinecrafted** [comment]
yea but how do you get the meat? we need polar bears first

**Comment by ItzEnderYT0** [comment]
by killed them

**Comment by ItzEnderYT0** [comment]
and polar bears already exist in minecraft

**Comment by UKMinecrafted** [comment]
o wait yea they do
good suggestion

**Comment by UKMinecrafted** [comment]
this will be added in the next update

**Locked and closed**

**Comment by UKMinecrafted** [comment]
This has now been added just needs to be textured

**Comment by UKMinecrafted** [comment]
This has been added in beta 1.2 will be fully added this weekend

**Added and Closed**
